image: alpine:latest

pages:
  stage: deploy
  script:
    - echo 'Build GitLab Pages'
    # Rename »public« folder
    - mv web public
    # Change absolute paths
    - sed -i 's/\/assets/assets/g' web/index.html
  artifacts:
    paths:
      - public
  only:
    - master
